- name: Workstation
  hosts: localhost
  become: true

  vars:
    username: lecndu
    user_home: /home/{{ username }}

  roles: 
    - blotware
    - beekeeper
    - filezilla
    - vscode
    - brave
    - git
    - docker
    - php
    - composer
    - nodejs