- name: Uninstall Blotwares
  dnf:
    name:
      - kmines
      - kmahjongg
      - kpat
      # - ktnef
      # - kmail
      # - kmail-account-wizard
      # - kmail-libs
      # - kmailtransport
    state: absent
    autoremove: yes
