- name: Check if NodeJS is installed
  shell: which node
  register: nodejs_check
  changed_when: false
  failed_when: false

- name: DNF install NodeJS
  dnf:
    name: nodejs
    state: present
  when: nodejs_check.rc != 0 

